import { writeFileSync, mkdirSync, cpSync, existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { CONFIG_DIR, GENERATED_DIR, RUNTIME_DIR, INIT_FILE, PKG_ROOT } from "./paths.js";
import { toolById } from "./tools.js";
import type { Config } from "./config.js";

export function version(): string {
  try {
    return JSON.parse(readFileSync(join(PKG_ROOT, "package.json"), "utf8")).version ?? "0.0.0";
  } catch {
    return "0.0.0";
  }
}

const HEADER = (v: string) =>
  `# Generated by shellup v${v} on ${new Date().toISOString()}\n` +
  `# Do not edit — regenerated by \`shellup apply\`.\n` +
  `# Put your own overrides in ~/.config/shellup/custom.zsh, which is never touched.\n`;

function renderTools(config: Config): string {
  const parts: string[] = [HEADER(version())];
  for (const id of config.tools) {
    const tool = toolById(id);
    if (!tool || (!tool.snippet && !tool.sourceFiles)) continue;

    const rule = `\n# \u2500\u2500 ${tool.label} ${"\u2500".repeat(Math.max(0, 68 - tool.label.length))}\n`;
    const indent = (body: string) => body.split("\n").map((l) => (l.trim() ? `  ${l}` : l)).join("\n");

    if (tool.sourceFiles) {
      // A plugin: its settings must be set before the file loads, and the file
      // itself lives at a different path on every package manager. The anonymous
      // function keeps the loop variable out of the user's shell.
      parts.push(
        rule +
          (tool.snippet ? tool.snippet + "\n" : "") +
          `() {\n  local p\n  for p in \\\n` +
          tool.sourceFiles.map((f) => `    "${f}"`).join(" \\\n") +
          `\n  do\n    [[ -r $p ]] && { source $p; break }\n  done\n}\n`,
      );
      continue;
    }

    // A binary: guarded so an uninstalled or later-removed tool is a no-op,
    // never a broken shell.
    parts.push(rule + `if command -v ${tool.bin} >/dev/null 2>&1; then\n` + indent(tool.snippet!) + `\nfi\n`);
  }
  return parts.join("");
}

function renderInit(config: Config): string {
  const lines = [
    HEADER(version()),
    "",
    `export SHELLUP_DIR="\${SHELLUP_DIR:-${CONFIG_DIR.replace(process.env.HOME ?? "", "$HOME")}}"`,
    `export SHELLUP_VERSION="${version()}"`,
    "",
    "# Non-interactive shells (scripts, scp, rsync) get nothing: sourcing a prompt",
    "# engine there is wasted work and can break protocols that expect clean stdout.",
    '[[ -o interactive ]] || return 0',
    "",
    "shellup_source() { [ -r \"$1\" ] && source \"$1\"; }",
    "",
  ];

  if (config.functions || config.aliases || config.keybindings) lines.push("# ── defaults");
  lines.push(`shellup_source "$SHELLUP_DIR/runtime/options.zsh"`);
  lines.push("");
  lines.push("# ── prompt (engine first, then the theme that renders its variables)");
  lines.push(`shellup_source "$SHELLUP_DIR/runtime/prompt.zsh"`);
  lines.push(`shellup_source "$SHELLUP_DIR/runtime/themes/${config.theme}.zsh"`);
  lines.push("");
  if (config.aliases) lines.push(`shellup_source "$SHELLUP_DIR/runtime/aliases.zsh"`);
  if (config.functions) lines.push(`shellup_source "$SHELLUP_DIR/runtime/functions.zsh"`);
  if (config.keybindings) lines.push(`shellup_source "$SHELLUP_DIR/runtime/keybindings.zsh"`);
  lines.push("");
  lines.push("# ── tool integrations (last, so tools like fzf bind their own keys over ours)");
  lines.push(`shellup_source "$SHELLUP_DIR/generated/tools.zsh"`);
  lines.push("");
  lines.push("# ── yours, always last and never regenerated");
  lines.push(`shellup_source "$SHELLUP_DIR/custom.zsh"`);
  lines.push("");
  return lines.join("\n");
}

/** Writes the whole generated tree. Safe to run repeatedly. */
export function apply(config: Config): void {
  mkdirSync(CONFIG_DIR, { recursive: true });
  mkdirSync(GENERATED_DIR, { recursive: true });

  cpSync(join(PKG_ROOT, "runtime"), RUNTIME_DIR, { recursive: true });
  writeFileSync(join(GENERATED_DIR, "tools.zsh"), renderTools(config), "utf8");
  writeFileSync(INIT_FILE, renderInit(config), "utf8");

  const custom = join(CONFIG_DIR, "custom.zsh");
  if (!existsSync(custom)) {
    writeFileSync(
      custom,
      "# Your own shell config. shellup never overwrites this file.\n" +
        "# It is sourced last, so anything here wins over shellup's defaults.\n\n",
      "utf8",
    );
  }
}
